import { DEFAULT_KB_CONFIG } from "../../config/defaults";

export const KB_CONFIG_TEMPLATE = `${JSON.stringify(DEFAULT_KB_CONFIG, null, 2)}\n`;

export const GRAPH_JSON_TEMPLATE = `${JSON.stringify(
  {
    version: 1,
    lastUpdated: null,
    nodes: { categories: {}, articles: {} },
    edges: { functional: [], dependency: [] },
  },
  null,
  2,
)}\n`;

export const INDEX_MD_TEMPLATE = `# Knowledge Base Index

> Auto-generated by \`kb index\`. Do not edit manually.

_No articles yet. Run \`kb ingest <topic>\` and then \`kb compile\`._
`;

export const LOG_MD_TEMPLATE = `# Activity Log

> Append-only. Each entry is added by \`kb\` commands automatically.
`;

export const GITIGNORE_TEMPLATE = `node_modules/
.DS_Store
*.log
.env
.env.local
dist/
.nuxt/
.output/
`;

export const NUXT_CONFIG_TEMPLATE = `// Docus configuration for the KB site.
// See https://docus.dev for documentation.
export default defineNuxtConfig({
  extends: ["@docus/docs"],
  content: {
    sources: {
      wiki: {
        driver: "fs",
        prefix: "/wiki",
        base: "./wiki",
      },
    },
  },
});
`;
